[project]
name = "qt-parameters"
version = "1.4.1"
description = "Qt parameter widgets and forms for Python."
authors = [
    {name = "Beat Reichenbach"}
]
dependencies = [
    "qtpy>=2.0,<3"
]
requires-python = ">=3.9"
license = "MIT"
readme = "README.md"

[project.optional-dependencies]
dev = [
    "pre-commit>=4.0",
    "python-semantic-release>=9.0",
    "pytest>=8.0",
    "qt-material-icons>=0.2,<1",
    "ruff>=0.16",
    "ty>=0.0.82",
    "qt-themes>=0.2",
    "PySide6>=6.0",
]
pyside2 = ["PySide2"]
pyside6 = ["PySide6"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["qt_parameters*"]

[tool.setuptools.package-data]
qt_parameters = ["py.typed", "**/resources"]

[tool.semantic_release]
allow_zero_version = true
version_variables = ["qt_parameters/__init__.py:__version__"]
version_toml  = ["pyproject.toml:project.version"]

[tool.semantic_release.remote]
ignore_token_for_push = true

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["E", "W", "F", "I", "UP", "B", "SIM", "ANN", "RUF"]
ignore = ["SIM108", "SIM102"]

[tool.pytest.ini_options]
log_cli = true
log_level = "INFO"

[tool.ty.src]
exclude = ["**/resources"]

[tool.ruff]
extend-exclude = ["**/resources"]
